version: '3.6'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - product-app
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    volumes:
      - "zookeeper_data:/var/lib/zoo_Data"
  
  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - product-app
    depends_on:
      - zookeeper
    volumes:
      - "kafka_data:/var/lib/kafka_data"
    ports:
      - 9093:9093
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:29093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:9093,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redpanda:
    networks:
      - product-app
    image: docker.redpanda.com/redpandadata/console:latest
    restart: always
    container_name: redpanda-console
    environment:
       KAFKA_BROKERS: kafka:9093
    ports:
      - "8090:8080"
    depends_on:
      - kafka
  
  product-command-app:
    container_name: product-command-app
    networks:
      - product-app
    restart: always
    image: product-command-app
    build: ./
    environment:
      - spring.kafka.producer.bootstrap-servers=kafka:9093
      - spring.data.mongodb.host=product-command-db
      - spring.data.mongodb.port=27017
    ports:
      - "8086:8084"
    depends_on:
      - product-command-db

  product-command-db:
    container_name: product-command-db
    networks:
      - product-app
    restart: always
    image: "mongo:latest"
    ports:
      - "27018:27017"
    volumes:
      - product_command_db_data:/data/db
  

  product-query-db:
    container_name: product-query-db
    networks:
      - product-app
    restart: always
    image: "mongo:latest"
    ports:
      - "27019:27017"
    volumes:
    - product_query_db_data:/data/db
  
  product-query-app:
    container_name: product-query-app
    networks:
      - product-app
    restart: always
    image: product-query-app
    build: ./
    environment:
      - spring.kafka.consumer.bootstrap-servers=kafka:9093
      - spring.data.mongodb.host=product-query-db
      - spring.data.mongodb.port=27017
    ports:
      - "8087:8085"
    depends_on:
      - product-query-db

volumes:
  product_query_db_data:
  product_command_db_data:
  zookeeper_data:
  kafka_data:

networks:
  product-app:
    driver: bridge