server:
  port: 8084
  servlet:
    context-path: /api/v1
spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: product_command_management
  kafka:
    producer:
      bootstrap-servers: localhost:29093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.example.product.command.serializers.CustomSerializer

    
